spring:
  datasource:
    url: jdbc:oracle:thin:@//localhost:1521/XE
    username: oracleadmin
    password: oracleadmin
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl